[MI-2460] Fix security issues
Brightscout/mattermost-plugin-servicenow pull request #15
Opened 2022-12-14 13:34 UTC by ayusht2810

Fix security issues:
https://github.com/mattermost/mattermost-plugin-servicenow/issues/144
https://github.com/mattermost/mattermost-plugin-servicenow/issues/146
https://github.com/mattermost/mattermost-plugin-servicenow/issues/147
https://github.com/mattermost/mattermost-plugin-servicenow/issues/148
https://github.com/mattermost/mattermost-plugin-servicenow/issues/149
https://github.com/mattermost/mattermost-plugin-servicenow/issues/150

2022-12-14 15:43 UTC, raghavaggarwal2308 requested changes

2022-12-14 16:11 UTC, ayusht2810 commented on server/plugin/api.go
> +		p.handleAPIError(w, &serializer.APIErrorResponse{StatusCode: http.StatusInternalServerError, Message: permissionErr.Error()})
it is already been done in the function `HasChannelPermissions`

2022-12-14 16:15 UTC, raghavaggarwal2308 approved these changes

2022-12-15 07:21 UTC, raghavaggarwal2308 approved these changes

2022-12-15 08:28 UTC, Kshitij-Katiyar commented on server/plugin/api_test.go
> +		"user do not have the permissions for the subscriptions channel": {
```suggestion
		"user does not have permission for the subscriptions channel": {
```

2022-12-15 08:28 UTC, Kshitij-Katiyar commented on server/plugin/api_test.go
> +		"user do not have the permission to set subscription for this channel": {
```suggestion
		"user does not have permission to set the subscription for this channel": {
```

2022-12-15 08:28 UTC, Kshitij-Katiyar commented on server/plugin/command_test.go
> +			params:      []string{"me", "all_channels"},
are there constant for these

2022-12-15 08:45 UTC, Kshitij-Katiyar approved these changes

2022-12-15 08:49 UTC, manojmalik20 commented on server/plugin/http.go
> +		updatedError := strings.ReplaceAll(err.Error(), c.plugin.getConfiguration().MattermostSiteURL, "")
```suggestion
		updatedError := strings.ReplaceAll(err.Error(), c.plugin.getConfiguration().ServiceNowBaseURL, "")
```
We have to replace the ServiceNow URL as we are making request to that URL.

2022-12-15 13:55 UTC, manojmalik20 commented on server/plugin/util.go
> +func (p *Plugin) HasChannelPermissions(userID, channelID string) (bool, int, error) {
Is there really a need for the `bool` return type?

2022-12-15 16:22 UTC, manojmalik20 approved these changes

2022-12-15 16:22 UTC, manojmalik20 commented on server/plugin/api_test.go
> +		"user do not have the permission to share record in the channel": {
```suggestion
		"user does not have the permission to share record in the channel": {
```

2022-12-15 16:22 UTC, manojmalik20 commented on server/plugin/api_test.go
> +		"user do not have the permission to create subscription for this channel": {
```suggestion
		"user does not have permission to create a subscription for this channel": {
```

2022-12-15 16:22 UTC, manojmalik20 commented on server/plugin/api_test.go
> +			  	}`, testutils.GetID(), testutils.GetChannelID()),
Why have you changed this everywhere?

2022-12-15 16:22 UTC, manojmalik20 commented on server/plugin/api_test.go
> +				})
Why is this inside `SetupClient`? Shouldn't it be inside `SetupPlugin`? 
Fix this everywhere.

2022-12-15 16:22 UTC, manojmalik20 commented on server/plugin/api_test.go
> +		"user does not have permission to set the subscription for this channel": {
```suggestion
		"user does not have permission to edit the subscription for this channel": {
```

2022-12-15 16:22 UTC, manojmalik20 commented on server/plugin/command_test.go
> +			description: "HandleListSubscriptions: User do not have permissions for the subscriptions channel",
```suggestion
			description: "HandleListSubscriptions: User does not have permissions for the subscriptions in the channel",
```

2022-12-15 16:54 UTC, merged