[MI-2473] Create custom post for subscription notifications and share…
Brightscout/mattermost-plugin-servicenow pull request #19
Opened 2022-12-19 07:31 UTC by ayusht2810

… record post

1. Create custom posts for shared record posts and subscription notifications.
2. Fix the issue of the comment modal and update state modal opening on multiple clients.

2022-12-20 05:59 UTC, raghavaggarwal2308 requested changes

2022-12-20 05:59 UTC, raghavaggarwal2308 commented on webapp/src/containers/custom_posts/notificationPost.tsx
> +        if (headerCols.length > 0) {
```suggestion
        if (headerCols.length) {
```

2022-12-20 06:42 UTC, ayusht2810 commented on webapp/src/containers/custom_posts/notificationPost.tsx
> +        let nrTables = 0;
this is used as a unique key for the table element

2022-12-20 07:04 UTC, ayusht2810 commented on webapp/src/containers/custom_posts/notificationPost.tsx
> +        let nrTables = 0;
no

2022-12-20 09:35 UTC, raghavaggarwal2308 approved these changes

2022-12-26 17:16 UTC, manojmalik20 commented on webapp/src/plugin_constants/index.ts
>      ASSIGNMENT_GROUP = 'assignment_group',
The name of this enum can be `RecordDataConfigKeys`

2022-12-26 17:16 UTC, manojmalik20 commented on webapp/src/utils/index.tsx
> +    key === RecordDataLabelConfigKey.ASSIGNMENT_GROUP ||
You can create a `Set` for this as well.

2022-12-29 09:11 UTC, ayusht2810 commented on webapp/src/containers/addOrViewComments/index.tsx
> +        }, 500);
removed this time now

2022-12-29 09:12 UTC, ayusht2810 commented on webapp/src/containers/addOrViewComments/index.tsx
> +        setTimeout(() => {
I don't think we need that as we have removed time from it

2022-12-29 09:15 UTC, ayusht2810 commented on webapp/src/containers/updateState/index.tsx
> +        setTimeout(() => {
same

2022-12-29 09:38 UTC, manojmalik20 approved these changes

2022-12-29 10:53 UTC, sooraj-shukla requested changes

2022-12-29 10:53 UTC, sooraj-shukla commented on webapp/src/containers/custom_post/styles.scss
> +        border-left-width: 4px;
border-left: 4px solid rgba(35, 137, 215, 0.5);

2022-12-29 10:53 UTC, sooraj-shukla commented on webapp/src/containers/custom_post/styles.scss
> +        border-left-color: rgba(35, 137, 215, 0.5);
```suggestion
```

2022-12-29 10:53 UTC, sooraj-shukla commented on webapp/src/containers/custom_post/styles.scss
> +            font-weight: 600;
Please check if we've util classes for font weights.

2022-12-29 11:18 UTC, sooraj-shukla approved these changes

2022-12-29 11:30 UTC, merged