Show filters in RHS, events panel and while listing subscriptions
Brightscout/mattermost-plugin-servicenow pull request #41
Opened 2023-01-31 08:40 UTC by ayusht2810

2023-02-01 11:40 UTC, raghavaggarwal2308 requested changes

2023-02-01 11:40 UTC, raghavaggarwal2308 commented on server/plugin/util.go
> +		}
```suggestion
	        filterValue = filterValue[1 : len(filterValue)-1]
		if index == len(filters)-1 {
			filterValue = filterValue[1 : len(filterValue)-2]
		} 
```

2023-02-01 11:40 UTC, raghavaggarwal2308 commented on server/plugin/util.go
> +		}
same

2023-02-01 11:40 UTC, raghavaggarwal2308 commented on server/serializer/subscription.go
> +		filtersData = "N/A "
```suggestion
		filtersData = "N/A"
```
Ignore if it was intentional

2023-02-01 11:40 UTC, raghavaggarwal2308 commented on webapp/src/components/chip/index.tsx
> +        >{text}</div>
```suggestion
    <Tooltip tooltipContent={text}>
        <div className={`servicenow-chip Badge__box ${extraClass}`}>
            {text}
        </div>
```
maybe?

2023-02-01 11:40 UTC, raghavaggarwal2308 commented on webapp/src/containers/Rhs/rhs.scss
> +      margin: 1px 5px 0px -7px;
Can we avoid the negative margin?

2023-02-01 12:19 UTC, ayusht2810 commented on server/serializer/subscription.go
> +		filtersData = "N/A "
yes, it was intentional

2023-02-02 06:53 UTC, raghavaggarwal2308 approved these changes

2023-02-06 09:13 UTC, manojmalik20 commented on webapp/src/containers/Rhs/rhs.scss
> +    width: 100%;
Indentation is wrong here. Also, please get the CSS reviewed by a FE dev.

2023-02-06 09:13 UTC, manojmalik20 commented on webapp/src/containers/addOrEditSubscriptions/subComponents/eventsPanel.tsx
> +                                    <div key={filter.filterValue ?? ''}>
```suggestion
                                    <div key={filter.filterValue}>
```
Not needed because of the condition on above line.

2023-02-06 11:32 UTC, ayusht2810 commented on server/serializer/subscription.go
> +		filtersData = "N/A "
updated the logic now

2023-02-06 11:34 UTC, ayusht2810 commented on webapp/src/components/chip/index.tsx
> +
discussed and created ticket https://brightscout.atlassian.net/browse/MI-2728

2023-02-06 11:36 UTC, ayusht2810 commented on webapp/src/containers/addOrEditSubscriptions/subComponents/filtersPanel.tsx
> -                    disabled={assignmentGroupDataLoading}
we were loading filter values previously by calling API but now we are directly sending them from API, so this wasn't needed

2023-02-06 11:43 UTC, sooraj-shukla approved these changes

2023-02-06 15:07 UTC, manojmalik20 approved these changes

2023-02-06 15:11 UTC, merged