[MI-2112] Added support for bulk subscriptions and in all APIs and sl…
Brightscout/mattermost-plugin-servicenow pull request #42
Opened 2022-09-01 09:10 UTC by manojmalik20

…ash commands

Modified the client function for checking duplicate subscription and added filter for subscription type in Get all subscriptions
Made some small changes in slash commands for listing and editing subscriptions
Modified the logic in the util functions for filtering subscriptions and parsing subscriptions
Modified the validations while creating subscription and editing subscription

2022-09-01 09:47 UTC, raghavaggarwal2308 requested changes

2022-09-01 09:47 UTC, raghavaggarwal2308 commented on server/http.go
> +			return nil, http.StatusInternalServerError, ErrorContentTypeNotJSON
Are we sure that we are always gonna get this error when content type is not json?
I think it should be `invalid character` only

2022-09-01 09:49 UTC, manojmalik20 commented on server/http.go
> +			return nil, http.StatusInternalServerError, ErrorContentTypeNotJSON
Yes, we are sure because it always return HTML response when it's not JSON.

2022-09-01 09:50 UTC, raghavaggarwal2308 commented on server/http.go
> +			return nil, http.StatusInternalServerError, ErrorContentTypeNotJSON
okay

2022-09-01 09:50 UTC, raghavaggarwal2308 approved these changes

2022-09-01 09:53 UTC, ayusht2810 approved these changes

2022-09-08 08:43 UTC, avas27JTG commented on server/api.go
> +	// because after "WriteHeader" is called, no headers can be set, so we have to set it before the call to "WriteHeader"
```suggestion
	// because after "WriteHeader" is called, no headers can be set, so, we have to set it before the call to "WriteHeader"
```

2022-09-08 08:43 UTC, avas27JTG commented on server/api.go
>  	w.WriteHeader(statusCode)
can't we write the header after `returnStatusOK(w)`

2022-09-08 08:43 UTC, avas27JTG commented on server/client.go
> +	// subscriptionType will be intentionally sent empty string if we have to return subscriptions of all types
```suggestion
	// subscriptionType will be intentionally sent an empty string if we have to return subscription of all types
```

2022-09-08 08:43 UTC, avas27JTG commented on server/constants/constants.go
> +		SubscriptionTypeRecord: true,
```suggestion
		IsSubscriptionTypeRecord: true,
```

2022-09-08 08:43 UTC, avas27JTG commented on server/constants/constants.go
> +		SubscriptionTypeBulk:   true,
```suggestion
		IsSubscriptionTypeBulk:   true,
```

2022-09-08 08:43 UTC, avas27JTG commented on server/serializer/subscription.go
> +		}
```suggestion
		if s.RecordID == nil {
			return fmt.Errorf("recordID is required")
		}
		
		if valid, err := regexp.MatchString(constants.ServiceNowSysIDRegex, *s.RecordID); err != nil || !valid {
			return fmt.Errorf("recordID is not valid")
		}
```

2022-09-08 08:43 UTC, avas27JTG commented on server/util.go
> +	if recordSubscriptions.Len() > 0 {
have we handled case when `recordSubscriptions or bulkSubscriptions` are <= 0?

2022-09-12 14:51 UTC, manojmalik20 commented on server/api.go
> +	// because after "WriteHeader" is called, no headers can be set, so we have to set it before the call to "WriteHeader"
This will not be the correct punctuation. Grammarly is also against it.

2022-09-12 14:55 UTC, manojmalik20 commented on server/api.go
>  	w.WriteHeader(statusCode)
No, because inside `returnStatusOK`, we are calling `w.Write` and it automatically sets the status code to `200` and it can't be overwritten after that.

2022-09-12 14:57 UTC, manojmalik20 commented on server/constants/constants.go
> +		SubscriptionTypeRecord: true,
This is not what you're thinking. Please see the whole file to understand the context here. We should not change this variable name.

2022-09-12 14:57 UTC, manojmalik20 commented on server/constants/constants.go
> +		SubscriptionTypeBulk:   true,
Same.

2022-09-12 14:59 UTC, manojmalik20 commented on server/util.go
> +	if recordSubscriptions.Len() > 0 {
Yes, that is already handled. If there are no subscriptions, this function is not even called.

2022-09-13 06:28 UTC, avas27JTG commented on server/constants/constants.go
> +		SubscriptionTypeRecord: true,
isn't this a boolean type always?

2022-09-13 06:29 UTC, avas27JTG approved these changes

2022-09-14 08:34 UTC, manojmalik20 commented on server/constants/constants.go
> +		SubscriptionTypeRecord: true,
This is a map of string vs bool. And `SubscriptionTypeRecord` is a constant variable whose value is "record".

2022-09-14 08:34 UTC, merged