[MI-2150] Add testcases for auth_token and bot file
Brightscout/mattermost-plugin-servicenow pull request #50
Opened 2022-09-14 10:12 UTC by ayusht2810

2022-09-16 05:17 UTC, raghavaggarwal2308 requested changes

2022-09-16 05:17 UTC, raghavaggarwal2308 commented on server/auth_token_test.go
> +func (a *mockAesgcm) NonceSize() int { return 1 }
```suggestion
func (a *mockAesgcm) NonceSize() int { return 0 }
```
The default value of int is 0. Change in the next func also

2022-09-16 05:17 UTC, raghavaggarwal2308 commented on server/bot_test.go
> +			_, err := p.DM("mockUserID", "mockFormat")
Can we add a check for the first value as well?

2022-09-16 10:09 UTC, Kshitij-Katiyar commented on server/auth_token_test.go
> +			description:    "NewEncodedAuthToken: failed to create oAuth token because aes.NewCipher gives error",
Check this everywhere
```suggestion
			description:    "NewEncodedAuthToken: failed to create the oAuth token because aes.NewCipher gives error",
```

2022-09-16 10:09 UTC, Kshitij-Katiyar commented on server/auth_token_test.go
> +
remove this line

2022-09-16 10:09 UTC, Kshitij-Katiyar commented on server/auth_token_test.go
> +				return 1, testCase.readFullError
```suggestion
				return 0, testCase.readFullError
```

2022-09-27 06:13 UTC, ayusht2810 commented on server/auth_token_test.go
> +func (a *mockAesgcm) NonceSize() int { return 1 }
test case fails on changing this value to 0

2022-09-27 08:02 UTC, raghavaggarwal2308 approved these changes

2022-09-27 08:04 UTC, Kshitij-Katiyar approved these changes

2022-09-27 17:44 UTC, manojmalik20 commented on server/plugin/auth_token_test.go
> +		readFullError  error
Instead of defining three different errors, define a function here that will apply the monkey patches. You can take a reference from other test files like `api_test.go` or `user_test.go`.

2022-09-27 17:44 UTC, manojmalik20 commented on server/plugin/bot_test.go
> +			mockChannelErr: &model.AppError{},
You can `model.AppError` from testutils. There are functions already present for this.

2022-09-27 17:44 UTC, manojmalik20 commented on server/plugin/bot_test.go
> +			mockAPI.On("LogError", testutils.GetMockArgumentsWithType("string", 5)...).Return("LogInfo error")
I think it should be "LogInfo" here and also, do this in a function which will be in the struct. Take a reference from other test files.

2022-09-28 06:57 UTC, ayusht2810 commented on server/plugin/auth_token_test.go
> +		readFullError  error
updated this, but is there any specific reason for mocking them in struct instead of mocking them separately? I think it's easier to define them once and then return different errors from them.

2022-09-28 08:08 UTC, manojmalik20 approved these changes

2022-09-28 08:08 UTC, manojmalik20 commented on server/plugin/bot_test.go
> +				a.On("LogError", testutils.GetMockArgumentsWithType("string", 5)...).Return("LogError error")
```suggestion
				a.On("LogError", testutils.GetMockArgumentsWithType("string", 5)...).Return()
```
LogError has no return type.

2022-09-28 08:09 UTC, manojmalik20 commented on server/plugin/auth_token_test.go
> +		readFullError  error
It's just because we don't need to patch all the functions in all the test cases. In the other approach, we are patching all the functions irrespective of whether it's needed or not.

2022-09-28 09:04 UTC, merged