[MI-2976] Auto fill the caller field if the sender is connected to Se…
Brightscout/mattermost-plugin-servicenow pull request #50
Opened 2023-04-10 06:16 UTC by ayusht2810

…rviceNow

2023-04-10 07:34 UTC, Kshitij-Katiyar approved these changes

2023-04-10 07:46 UTC, raghavaggarwal2308 requested changes

2023-04-10 07:46 UTC, raghavaggarwal2308 commented on webapp/src/containers/createIncident/callerPanel.tsx
> +                const senderDetails = data?.filter((c) => c.mattermostUserID === senderId)[0];
Do we need to check the length here?

2023-04-10 07:47 UTC, raghavaggarwal2308 commented on webapp/src/containers/createIncident/callerPanel.tsx
> +                const senderDetails = data?.filter((c) => c.mattermostUserID === senderId)[0];
discussed

2023-04-10 07:47 UTC, ayusht2810 commented on webapp/src/containers/createIncident/callerPanel.tsx
> +                const senderDetails = data?.filter((c) => c.mattermostUserID === senderId)[0];
discussed

2023-04-10 07:47 UTC, raghavaggarwal2308 approved these changes

2023-04-10 10:11 UTC, manojmalik20 approved these changes

2023-04-10 10:11 UTC, manojmalik20 commented on webapp/src/containers/createIncident/callerPanel.tsx
> +                const senderDetails = data?.filter((c) => c.mattermostUserID === senderId)[0];
Use `find` instead of `filter`.

2023-04-11 09:39 UTC, manojmalik20 approved these changes

2023-04-11 09:42 UTC, merged