[MI-2171] Added unit tests for configuration.go, http.go, kv.go, user.go
Brightscout/mattermost-plugin-servicenow pull request #57
Opened 2022-09-21 10:26 UTC by manojmalik20

2022-09-22 10:43 UTC, raghavaggarwal2308 requested changes

2022-09-22 10:43 UTC, raghavaggarwal2308 commented on server/plugin/kv_test.go
> +					return fmt.Errorf("user store error")
```suggestion
					return fmt.Errorf("store user error")
```

2022-09-22 10:43 UTC, raghavaggarwal2308 commented on server/plugin/kv_test.go
> +					return fmt.Errorf("user load error")
```suggestion
					return fmt.Errorf("load user error")
```

2022-09-22 10:43 UTC, raghavaggarwal2308 commented on server/plugin/kv_test.go
> +			_, err := s.LoadUser("mock-userID")
can we add a check for res as well?

2022-09-23 10:37 UTC, Kshitij-Katiyar commented on server/plugin/http_test.go
> +}
Here i think we should also write the test case for Call Function as well

2022-09-23 10:37 UTC, Kshitij-Katiyar commented on server/plugin/user_test.go
> +			description: "OAuth2 is initialized successfully",
Please write a better description not able to understand this

2022-09-23 10:37 UTC, Kshitij-Katiyar commented on server/plugin/user_test.go
> +			authedUserID: "mockUserID",
Better naming than authedUserID it could be autheticatedUserID or something

2022-09-23 10:37 UTC, Kshitij-Katiyar commented on server/plugin/user_test.go
> +		"user ID mismatch": {
Would be similar to above
```suggestion
		"failed to match user ID": {
```

2022-09-23 10:37 UTC, Kshitij-Katiyar commented on server/plugin/user_test.go
> +			expectedErrorMessage: "mockErrMessage",
Please have you mock Err messages related to description like you have in above test and check this everywhere

2022-09-23 10:37 UTC, Kshitij-Katiyar commented on server/plugin/user_test.go
> +			expectedErrorMessage: "store user error",
change all of these according to above comment

2022-09-27 09:46 UTC, manojmalik20 commented on server/plugin/http_test.go
> +}
Deferring this for now. Added TODO comment.

2022-09-27 09:52 UTC, Kshitij-Katiyar approved these changes

2022-09-27 10:18 UTC, Kshitij-Katiyar commented on server/plugin/http_test.go
> +}
i was not able to find the TODO comment if you have added it resolve this comment if not please add it

2022-09-27 12:01 UTC, raghavaggarwal2308 approved these changes

2022-09-28 15:38 UTC, avas27JTG commented on server/plugin/kv_test.go
> +			description: "User is loaded successfully from KV store using mattermostID",
```suggestion
			description: "User is loaded successfully from the KV store using mattermostID",
```

2022-09-28 15:38 UTC, avas27JTG commented on server/plugin/kv_test.go
> +			description: "User is not loaded successfully from KV store",
```suggestion
			description: "User is not loaded successfully from the KV store",
```

2022-09-28 15:38 UTC, avas27JTG commented on server/plugin/user_test.go
> +			expectedErrorMessage: "missing user, code or state",
same as above for messages

2022-09-29 05:47 UTC, avas27JTG approved these changes

2022-09-29 09:09 UTC, merged