[MI-2159] Test cases for some components
Brightscout/mattermost-plugin-servicenow pull request #59
Opened 2022-09-27 07:45 UTC by ayusht2810

2022-10-05 06:38 UTC, sooraj-shukla requested changes

2022-10-05 06:38 UTC, sooraj-shukla commented on webapp/package.json
> +    "react-bootstrap": "1.0.0",
Why we degraded the packages?

2022-10-05 06:38 UTC, sooraj-shukla commented on webapp/src/components/admin_settings/download_button.test.tsx
> +        component.unmount();
Do we really need to call unmount after each test if we're doing shallow rendering?

2022-10-05 06:38 UTC, sooraj-shukla commented on webapp/src/containers/addOrEditSubscriptions/addSubscription/addSubscription.test.tsx
> +        component.unmount();
Same as above.

2022-10-05 06:38 UTC, sooraj-shukla commented on webapp/src/containers/addOrEditSubscriptions/addSubscription/addSubscription.test.tsx
> +    it('Should render the edit subscription body correctly', () => {
Aren't we testing for add subscription here? I guess it should be `Should render the add subscription body correctly`

2022-10-05 06:38 UTC, sooraj-shukla commented on webapp/src/containers/addOrEditSubscriptions/addSubscription/addSubscription.test.tsx
> +});
I guess we should also add a test to check whether the `editSubscriptionData`(`pluginState.openEditSubscriptionModalReducer.data` the data passed as `subscriptionData` prop) is falsy, if possible.

2022-10-05 06:38 UTC, sooraj-shukla commented on webapp/src/containers/addOrEditSubscriptions/editSubscription/editSubscription.test.tsx
> +    it('Should render the edit subscription body correctly', () => {
I guess we should also add a test to check whether the `subscriptionData` is correctly passed and is not null, if possible.

2022-10-05 06:38 UTC, sooraj-shukla commented on webapp/src/containers/addOrEditSubscriptions/subComponents/eventsPanel.test.tsx
> +        expect(component.find('ModalSubtitleAndError')).toHaveLength(1);
Shouldn't we also test that `ModalSubstitleAndError` isn't rendered if the error is not passed.

2022-10-05 06:38 UTC, sooraj-shukla commented on webapp/src/containers/addOrEditSubscriptions/subComponents/eventsPanel.test.tsx
> +                cancelBtnText='Back'
I guess we should also test the footer functionality as well, like check when the buttons are disabled the handlers shouldn't be called when these are enabled the handlers should be called, at least for one of the components.

2022-10-05 07:15 UTC, ayusht2810 commented on webapp/package.json
> +    "react-bootstrap": "1.0.0",
we were getting some errors like `react jsx/runtime` and some type errors. we needed to upgrade either react version or downgrade these packages. so downgraded them

2022-10-05 07:16 UTC, ayusht2810 commented on webapp/src/containers/addOrEditSubscriptions/addSubscription/addSubscription.test.tsx
> +    it('Should render the edit subscription body correctly', () => {
removed these test files as on mounting, we were getting states as undefined

2022-10-05 07:17 UTC, ayusht2810 commented on webapp/src/containers/addOrEditSubscriptions/addSubscription/addSubscription.test.tsx
> +});
same

2022-10-05 07:17 UTC, ayusht2810 commented on webapp/src/containers/addOrEditSubscriptions/editSubscription/editSubscription.test.tsx
> +    it('Should render the edit subscription body correctly', () => {
same

2022-10-05 07:18 UTC, ayusht2810 commented on webapp/src/containers/addOrEditSubscriptions/subComponents/eventsPanel.test.tsx
> +                cancelBtnText='Back'
i don't think we need to test these functionality as it is already been tested in the mm UI library

2022-10-05 07:36 UTC, ayusht2810 commented on webapp/src/containers/addOrEditSubscriptions/subComponents/eventsPanel.test.tsx
> +        expect(component.find('ModalSubtitleAndError')).toHaveLength(1);
tried it, but this component will always be present, it is just rendering on basis of error

2022-10-05 09:56 UTC, ayusht2810 commented on webapp/src/containers/addOrEditSubscriptions/subComponents/eventsPanel.test.tsx
> +        expect(component.find('ModalSubtitleAndError')).toHaveLength(1);
updated this

2022-10-11 06:27 UTC, sooraj-shukla approved these changes

2022-10-11 09:10 UTC, manojmalik20 approved these changes

2022-10-11 10:42 UTC, manojmalik20 approved these changes

2022-10-11 10:42 UTC, manojmalik20 commented
Also check, if any snapshot needs to be updated.

2022-10-11 11:32 UTC, merged