[MI-2222] Add pagination on subscriptions in rhs
Brightscout/mattermost-plugin-servicenow pull request #69
Opened 2022-10-07 06:09 UTC by ayusht2810

2022-10-10 12:33 UTC, raghavaggarwal2308 requested changes

2022-10-10 12:33 UTC, raghavaggarwal2308 commented on webapp/src/containers/Rhs/index.tsx
> +    // Reset the page params and empty the subscription list
```suggestion
    // Reset the pagination params and empty the subscription list
```

2022-10-10 12:33 UTC, raghavaggarwal2308 commented on webapp/src/containers/Rhs/index.tsx
> +    // Reset states on changing channel or using toggle
```suggestion
    // Reset states on changing channel or using toggle switch
```

2022-10-10 12:33 UTC, raghavaggarwal2308 commented on webapp/src/containers/Rhs/rhsData.tsx
> +    ), [subscriptionList]);
shouldn't this contain paginationQuersParams as well?

2022-10-10 13:21 UTC, raghavaggarwal2308 approved these changes

2022-10-13 12:45 UTC, muazzamqazi commented on webapp/src/components/spinner/index.tsx
> +const Spinner = ({extraClass = ''}: { extraClass?: string }): JSX.Element => (
```suggestion
interface SpinnerProps { extraClass?: string };

const Spinner = ({extraClass = ''}: SpinnerProps): JSX.Element => (
```

2022-10-13 12:50 UTC, muazzamqazi commented on webapp/src/containers/Rhs/index.tsx
> +        setSubscriptionList(() => []);
```suggestion
        setSubscriptionList([]);
```

2022-10-13 12:56 UTC, muazzamqazi commented on webapp/src/containers/Rhs/rhsData.tsx
> +                            <p style={{textAlign: 'center'}}>
Can we use Bootstrap classes and avoid in-line styles?

2022-10-13 13:17 UTC, muazzamqazi approved these changes

2022-10-18 17:35 UTC, manojmalik20 commented on webapp/src/components/spinner/index.tsx
> +interface SpinnerProps { extraClass?: string }
Use proper indentation here.

2022-10-18 17:35 UTC, manojmalik20 commented on webapp/src/components/spinner/index.tsx
> +const Spinner = ({extraClass = ''}: SpinnerProps): JSX.Element => (
Shouldn't this component be in the UI library?

2022-10-18 17:35 UTC, manojmalik20 commented on webapp/src/containers/Rhs/index.tsx
> +        setPaginationQueryParams(() => ({page: Constants.DefaultPage, per_page: Constants.DefaultPageSize}));
```suggestion
        setPaginationQueryParams({page: Constants.DefaultPage, per_page: Constants.DefaultPageSize});
```
What's the need of providing a function here?

2022-10-18 17:35 UTC, manojmalik20 commented on webapp/src/containers/Rhs/index.tsx
> +        if (!subscriptionsState.isLoading && subscriptionsState.isSuccess) {
Move this `if` block inside the above `if` block.

2022-10-18 17:35 UTC, manojmalik20 commented on webapp/src/containers/Rhs/rhsData.tsx
> +        subscriptionList.length !== 0 && (subscriptionList.length - (paginationQueryParams.page * Constants.DefaultPageSize) === Constants.DefaultPageSize)
```suggestion
        subscriptionList.length > 0 && (subscriptionList.length - (paginationQueryParams.page * Constants.DefaultPageSize) === Constants.DefaultPageSize)
```
Can you explain this logic? I think it's wrong. :thinking:

2022-10-18 18:11 UTC, ayusht2810 commented on webapp/src/components/spinner/index.tsx
> +const Spinner = ({extraClass = ''}: SpinnerProps): JSX.Element => (
the spinner used in mm is different from ours so for now we kept it in SN

2022-10-18 18:12 UTC, ayusht2810 commented on webapp/src/containers/Rhs/rhsData.tsx
> +        subscriptionList.length !== 0 && (subscriptionList.length - (paginationQueryParams.page * Constants.DefaultPageSize) === Constants.DefaultPageSize)
updated the logic now

2022-10-19 08:33 UTC, manojmalik20 commented on webapp/src/containers/Rhs/index.tsx
> +            setSubscriptionList([...subscriptionList, ...subscriptions]);
Don't you need to check for `!isLoading`?

2022-10-19 08:33 UTC, manojmalik20 commented on webapp/src/containers/Rhs/rhsData.tsx
> +        (subscriptionList.length - (paginationQueryParams.page * Constants.DefaultPageSize) >= Constants.DefaultPageSize)
I think it's still wrong. Correct would be - 
```suggestion
        subscriptionList.length === Constants.DefaultPageSize
```

2022-10-19 08:41 UTC, ayusht2810 commented on webapp/src/containers/Rhs/rhsData.tsx
> +        (subscriptionList.length - (paginationQueryParams.page * Constants.DefaultPageSize) >= Constants.DefaultPageSize)
on thinking more I guess this logic was already correct `(subscriptionList.length - (paginationQueryParams.page * Constants.DefaultPageSize) === Constants.DefaultPageSize)` and `subscriptionList` is the total length of subscriptions, not just the list of current subscriptions fetched

2022-10-19 08:44 UTC, manojmalik20 commented on webapp/src/containers/Rhs/index.tsx
> +            setSubscriptionList([...subscriptionList, ...subscriptions]);
Okay, but you should still test this thoroughly.

2022-10-19 08:48 UTC, manojmalik20 commented on webapp/src/containers/Rhs/rhsData.tsx
> +        (subscriptionList.length - (paginationQueryParams.page * Constants.DefaultPageSize) >= Constants.DefaultPageSize)
I think you should change the variable name to `totalSubscriptions`.

2022-10-19 09:03 UTC, manojmalik20 approved these changes

2022-10-19 10:42 UTC, merged