[MI-2230] Add feature to search and share records
Brightscout/mattermost-plugin-servicenow pull request #73
Opened 2022-10-11 08:56 UTC by ayusht2810

2022-10-12 09:55 UTC, raghavaggarwal2308 approved these changes

2022-10-12 09:55 UTC, raghavaggarwal2308 commented on webapp/src/containers/shareRecords/index.tsx
> +                        placeholder={'Search Channel to share'}
```suggestion
                        placeholder={'Search channel to share'}
```

2022-10-18 08:39 UTC, sooraj-shukla requested changes

2022-10-18 08:39 UTC, sooraj-shukla commented on webapp/src/containers/addOrEditSubscriptions/subComponents/index.tsx
> +
Why this constant is created here and not in constants file?

2022-10-18 08:39 UTC, sooraj-shukla commented on webapp/src/containers/addOrEditSubscriptions/subComponents/recordTypePanel.test.tsx
> +];
This  is repetitive? We should move it to the constants file and import from there in both the files.

2022-10-18 18:10 UTC, manojmalik20 commented on webapp/src/containers/shareRecords/index.tsx
> +    const [error, setError] = useState<boolean>(false);
Is there really a need for this variable? Isn't one variable `apiError` enough?

2022-10-18 18:10 UTC, manojmalik20 commented on webapp/src/reducers/shareRecordModal/index.tsx
> +export type SubscriptionModalState = {
```suggestion
export type ShareRecordModalState = {
```

2022-10-19 05:46 UTC, ayusht2810 commented on webapp/src/containers/shareRecords/index.tsx
> +    const [error, setError] = useState<boolean>(false);
apiError is used in `ModalSubtitleAndError` as well. The required message will be printed twice once for `ChannelPanel` and `ModalSubtitleAndError` if we use one

2022-10-19 08:52 UTC, sooraj-shukla requested changes

2022-10-19 08:52 UTC, sooraj-shukla commented on webapp/src/models/plugin_api.d.ts
> +    kb_knowledge_base?: string | {display_value: string, link: string};
Can we create a type alias for `{display_value: string, link: string}` rather than repeating it again and again?

2022-10-19 08:52 UTC, sooraj-shukla commented on webapp/src/containers/shareRecords/index.tsx
> +                    confirmBtnText={'Share'}
```suggestion
                    confirmBtnText='Share'
```

2022-10-19 08:52 UTC, sooraj-shukla commented on webapp/src/containers/shareRecords/index.tsx
> +                    cancelBtnText={'Cancel'}
Fix this at all such places.

```suggestion
                    cancelBtnText='Cancel'
```

2022-10-19 08:52 UTC, sooraj-shukla commented on webapp/src/containers/shareRecords/index.tsx
> +            className={'rhs-modal'}
We don't need to wrap strings in curly braces.

2022-10-19 09:10 UTC, manojmalik20 commented on webapp/src/containers/shareRecords/index.tsx
> +    const [error, setError] = useState<boolean>(false);
Then, I guess this variable's name should be `showChannelValidationError`.

2022-10-19 09:53 UTC, manojmalik20 commented on webapp/src/containers/shareRecords/index.tsx
> +                <ModalSubtitleAndError error={apiError ?? ''}/>
Can you add a screenshot in the PR description showing this error?

2022-10-19 11:00 UTC, ayusht2810 commented on webapp/src/containers/addOrEditSubscriptions/subComponents/searchRecordsPanel.tsx
>              setApiResponseValid(true);
doing this gives eslint error

2022-10-19 11:01 UTC, ayusht2810 commented on webapp/src/containers/shareRecords/index.tsx
> +                <ModalSubtitleAndError error={apiError ?? ''}/>
added

2022-10-19 13:23 UTC, manojmalik20 commented on webapp/src/plugin_constants/index.ts
> +    CHANGE_REQUEST = 'change_request',
Then, you should change the type of `BulkSubscriptionHeaders` to something like this - `Record<Partial<RecordType>, string>`

2022-10-19 13:31 UTC, sooraj-shukla approved these changes

2022-10-19 17:41 UTC, manojmalik20 commented on webapp/src/containers/shareRecords/index.tsx
> +                            onConfirm={suggestionChosen ? shareRecord : null}
Intead of hiding the Share button, you should make it disabled.

2022-10-19 17:41 UTC, manojmalik20 commented on webapp/src/containers/shareRecords/index.tsx
> +    const [showRecordLoader, setShowRecordLoader] = useState(false);
What's the use of this?

2022-10-20 05:29 UTC, ayusht2810 commented on webapp/src/containers/shareRecords/index.tsx
> +                            onConfirm={suggestionChosen ? shareRecord : null}
this was done a/c to the figma

2022-10-20 05:29 UTC, ayusht2810 commented on webapp/src/containers/shareRecords/index.tsx
> +    const [showRecordLoader, setShowRecordLoader] = useState(false);
it was removed in the last commit

2022-10-20 09:03 UTC, manojmalik20 commented on webapp/src/containers/shareRecords/index.tsx
> +                            cancelDisabled={showModalLoader || (!recordData && suggestionChosen)}
What's the reason for disabling the Cancel button on this logic? I think it should only be disabled when loader is there.

2022-10-20 09:05 UTC, ayusht2810 commented on webapp/src/containers/shareRecords/index.tsx
> +                            cancelDisabled={showModalLoader || (!recordData && suggestionChosen)}
the same loader is used in the channel panel as well. But we want the buttons to be disabled till the record data is not null so that payload is not empty.

2022-10-20 09:08 UTC, manojmalik20 commented on webapp/src/containers/shareRecords/index.tsx
> +                            cancelDisabled={showModalLoader || (!recordData && suggestionChosen)}
Yeah, but why should we disable the "Cancel" button? The user should be able to click on Cancel and close the modal at any time.

Also, the "Share" button will not be visible until the record data is complete so I think there's no use of disabling that as well.

2022-10-20 09:17 UTC, ayusht2810 commented on webapp/src/containers/shareRecords/index.tsx
> +                            cancelDisabled={showModalLoader || (!recordData && suggestionChosen)}
updated the logic now

2022-10-20 09:22 UTC, manojmalik20 approved these changes

2022-10-20 09:38 UTC, merged