[MI-2285] Add test cases for util.go and kv.go
Brightscout/mattermost-plugin-servicenow pull request #90
Opened 2022-10-21 13:01 UTC by ayusht2810

2022-10-21 13:17 UTC, Kshitij-Katiyar commented on server/plugin/kv_test.go
> +	s := new(pluginStore)
```suggestion
	ps := new(pluginStore)
```

2022-10-21 13:17 UTC, Kshitij-Katiyar commented on server/plugin/kv_test.go
> +			description: "User is not loaded successfully from the KV store using mattermostID",
Is there any need for adding successfully in every test cases?
```suggestion
			description: "User is not loaded from the KV store using mattermostUserID",
```

2022-10-21 13:17 UTC, Kshitij-Katiyar commented on server/plugin/kv_test.go
> +			expectedError: "mockError",
we can have this variable of type error and below we can check for equal values in this you don't have to convert the actual error to string

2022-10-21 13:17 UTC, Kshitij-Katiyar commented on server/plugin/util_test.go
> +					ChannelID:          "mockChannelID",
create constants for variables which are same for all test cases

2022-10-21 14:17 UTC, Kshitij-Katiyar approved these changes

2022-11-03 06:42 UTC, raghavaggarwal2308 requested changes

2022-11-03 06:42 UTC, raghavaggarwal2308 commented on server/plugin/kv_test.go
> +					return nil, fmt.Errorf("mockError")
```suggestion
					return nil, fmt.Errorf("mockError")
```
Use something meaningful instead of "mockError". check everywhere

2022-11-03 07:09 UTC, ayusht2810 commented on server/plugin/kv_test.go
> +					return nil, fmt.Errorf("mockError")
We have used this at many places and in other plugins as well. I think it's fine to use it

2022-11-03 08:26 UTC, raghavaggarwal2308 commented on server/plugin/kv_test.go
> +					return nil, fmt.Errorf("mockError")
It was removed from VA. If it doesn't take much time we can fix it here as well. Otherwise this also fine.

2022-11-03 10:23 UTC, ayusht2810 commented on server/plugin/kv_test.go
> +					return nil, fmt.Errorf("mockError")
should we create a ticket for this, and update this after all test cases are merged @manojmalik20 ?

2022-11-11 10:06 UTC, manojmalik20 commented on server/plugin/kv_test.go
> +					return nil, fmt.Errorf("mockError")
Yes @ayusht2810 You can do this. Please create a ticket.

2022-11-11 10:47 UTC, manojmalik20 commented on server/plugin/util_test.go
> +		setupAPI    func(api *plugintest.API) *plugintest.API
```suggestion
		setupAPI    func(api *plugintest.API)
```

2022-11-11 10:47 UTC, manojmalik20 commented on server/plugin/util_test.go
> +				api.On("GetUser", testutils.GetID()).Return(&model.User{
You should sync this branch with `master`. There is a `GetUser` function in the testutils, you should use that here after modifying it.

2022-11-11 10:47 UTC, manojmalik20 commented on server/plugin/util_test.go
> +		setupAPI           func(api *plugintest.API) *plugintest.API
```suggestion
		setupAPI           func(api *plugintest.API)
```

2022-11-11 10:47 UTC, manojmalik20 commented on server/plugin/util_test.go
> +			description: "handleClientError: with update set not uploaded",
```suggestion
			description: "handleClientError: with latest update set not uploaded",
```

2022-11-11 10:47 UTC, manojmalik20 commented on server/plugin/util_test.go
> +		},
There is one more condition now if you take pull from the latest `master`. Please write the test case for that also.

2022-11-11 10:51 UTC, ayusht2810 commented on server/plugin/kv_test.go
> +					return nil, fmt.Errorf("mockError")
https://brightscout.atlassian.net/browse/MI-2351?atlOrigin=eyJpIjoiMDk1OTBmMDU0NDU3NDlkM2FjZTJkNTRkZjYzMGY2ZTEiLCJwIjoiaiJ9

created ticket for this

2022-11-11 11:34 UTC, manojmalik20 approved these changes

2022-11-11 13:32 UTC, raghavaggarwal2308 approved these changes

2022-11-11 13:33 UTC, merged