[MI-2307] Update readme files
Brightscout/mattermost-plugin-servicenow pull request #98
Opened 2022-10-31 07:30 UTC by ayusht2810

2022-10-31 08:41 UTC, raghavaggarwal2308 requested changes

2022-10-31 08:41 UTC, raghavaggarwal2308 commented on README.md
> +- Ability to open add and view comments/update state modal through buttons present in a notification post or a shared record post.
```suggestion
- Ability to open, add and view comments/update state modal through buttons present in a notification post or a shared record post.
```
Also, `view comments/update state modal` is sounding a little weird

2022-10-31 08:41 UTC, raghavaggarwal2308 commented on README.md
> +- Supported record types for sharing a record or updating a record state - incident, problem, change_request, kb_knowledge, task, change_task, cert_follow_on_task.
```suggestion
- Supported record types for sharing a record or updating a record state - incident, problem, change_request, kb_knowledge, task, change_task and cert_follow_on_task.
```

2022-10-31 10:28 UTC, Kshitij-Katiyar commented on README.md
> +- Ability to filter subscriptions in the Right Hand Sidebar using the filter icon.
```suggestion
- Ability to filter subscriptions in the Right-Hand Sidebar using the filter icon.
```

2022-10-31 10:28 UTC, Kshitij-Katiyar commented on docs/developer_docs.md
> +- Ability to filter subscriptions in the Right Hand Sidebar using the filter icon.
```suggestion
- Ability to filter subscriptions in the Right-Hand Sidebar using the filter icon.
```

2022-10-31 10:28 UTC, Kshitij-Katiyar commented on docs/developer_docs.md
> +- Ability to open search and share record modal through UI or by using a slash command.
```suggestion
- Ability to open search and share record modal through UI or slash command.
```

2022-10-31 15:29 UTC, ayusht2810 commented on README.md
> +- Ability to open add and view comments/update state modal through buttons present in a notification post or a shared record post.
updated the sentence

2022-11-01 06:18 UTC, Kshitij-Katiyar approved these changes

2022-11-08 09:52 UTC, raghavaggarwal2308 approved these changes

2022-11-10 11:32 UTC, ayusht2810 commented on README.md
> +- Supported record types for sharing a record or updating a record state - incident, problem, change_request, kb_knowledge, task, change_task and cert_follow_on_task.
updated types

2022-11-10 11:41 UTC, manojmalik20 approved these changes

2022-11-14 08:45 UTC, merged